# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql/my.cfg:/etc/my.cfg
      - ./volumes/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: airflow
      RABBITMQ_DEFAULT_PASS: airflow
      RABBITMQ_DEFAULT_VHOST: airflow
    ports:
      - 5672:5672
      - 15672:15672